### ISSUE TITLE
Report areas without connectors

### ISSUE THREAD

**Issue by madmaxoft** [madmaxoft/GalExport#24]
If there is an approved area that has no connectors, it should be reported by some tool, so that the admin can check for that. Usually this means forgotten connectors.

**Comment by madmaxoft** [comment]
Perhaps only if the intended use is not Trees, because Trees need no connectors.

**Comment by NiLSPACE** [comment]
Perhaps you can turn off the error for certain groups?

**Comment by madmaxoft** [comment]
Implemented in f84352e03ef4a3101fff00669219ee33079922e3
